### ISSUE TITLE
Typo in BERT slides

### ISSUE THREAD

**Issue by ChristophReich1996** [dl4nlp-tuda2021/deep-learning-for-nlp-lectures#23]
Hey @habernal, 
I guess there is a small typo in the [Wu, Y. et al, 2016] references of the BERT lecture slides (slide 66). 

arXive -> arXiv

PS: Very nice presentation of BERT :)

Cheers
Christoph

**Comment by habernal** [comment]
Good catch, fixed in bibtex (not PDF, it's just a tiny thing), thx!
